# Generated by Django 4.0.2 on 2022-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('F', 'Co-Founder'), ('E', 'Employee')], max_length=1)),
                ('description', models.TextField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='tags.Tag')),
            ],
        ),
    ]
