# Generated by Django 4.0.2 on 2022-02-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_web_site'),
        ('ads', '0002_remove_ad_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='startup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='startups.startup'),
            preserve_default=False,
        ),
    ]
