# Generated by Django 4.0.2 on 2022-03-08 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 8, 9, 17, 0, 498671, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
