# Generated by Django 4.0.2 on 2022-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('', 'Select'), ('F', 'Co-Founder'), ('E', 'Employee')], help_text='Please specify the position.', max_length=1),
        ),
    ]
