# Generated by Django 4.0.3 on 2022-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='share',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Please specify the share.', max_digits=4),
        ),
    ]
