# Generated by Django 4.0.2 on 2022-02-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
