# Generated by Django 4.0.2 on 2022-02-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='tags',
        ),
    ]
