# Generated by Django 4.0.2 on 2022-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_remove_startup_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
