# Generated by Django 4.0.2 on 2022-03-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_web_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
