# Generated by Django 4.0.2 on 2022-03-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_alter_startup_founded'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.SlugField>/photos'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
