# Generated by Django 4.0.2 on 2022-03-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_managers_and_more'),
        ('startups', '0010_remove_startup_photos_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
