# Generated by Django 4.0.2 on 2022-03-02 10:32

from django.db import migrations, models
import startups.models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0012_rename_propertyimage_startupimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=startups.models.image_dir_path),
        ),
    ]
