# Generated by Django 4.0.2 on 2022-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0016_alter_startup_description_alter_startup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
