# Generated by Django 4.0.2 on 2022-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0019_alter_startup_description_alter_startup_founded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='web_site',
            field=models.URLField(blank=True, help_text='Please enter the URL of your Startup.', null=True, verbose_name='Web-site'),
        ),
    ]
