# Generated by Django 4.0.2 on 2022-03-06 13:12

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0022_alter_startup_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='web_site',
            field=models.CharField(blank=True, help_text='Please enter the URL of your Startup.', max_length=200, null=True, validators=[config.validators.OptionalSchemeURLValidator()], verbose_name='Web-site'),
        ),
    ]
