# Generated by Django 4.0.3 on 2022-03-18 09:19

from django.db import migrations, models
import startups.models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0025_alter_startup_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='founded',
            field=models.DateField(db_index=True, help_text='Please enter the date when your startup was founded.', null=True, verbose_name='Founding Date'),
        ),
        migrations.AlterField(
            model_name='startupimage',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=startups.models.image_dir_path),
        ),
    ]
