# Generated by Django 4.0.2 on 2022-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        ('accounts', '0004_remove_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='startups',
            field=models.ManyToManyField(blank=True, null=True, to='startups.Startup'),
        ),
    ]
