# Generated by Django 4.0.2 on 2022-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('accounts', '0005_userprofile_about_userprofile_startups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
