# Generated by Django 4.0.2 on 2022-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_instagram_userprofile_mobile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
