# Generated by Django 4.0.2 on 2022-02-27 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
