# Generated by Django 4.0.2 on 2022-02-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registered',
        ),
    ]
